import {resolveLegacyIntent} from './support-legacy.mjs?v=20261006-results-final';
import {createSupportApp} from './support-app.mjs?v=20261006-results-final';
import {journeys} from './support-journeys.mjs?v=20261006-content-scope-1';
import {discover,discoveryFields,supplementalServices} from './support-discovery.mjs?v=20261006-results-final';
import {services,issues,regionLabels,routeMatchesRegion,routeContactURLs,routeWebActions} from './support-routing.mjs?v=20261006-continuous-final';
const home=[{"title":"Moving for a posting","href":"#task/posting","tasks":["posting"]},{"title":"Managing time apart","href":"#task/absence","tasks":["absence"]},{"id":"housing","title":"Housing, bills and essentials","tasks":["housing-tonight","losing-housing","stable-housing","rental","money","home-help","pets","nt-preparedness","home-ownership"]},{"id":"health","title":"Health and wellbeing","tasks":["mental-health","health","disability","bereavement","addiction","aboriginal-wellbeing","inclusive","private","urgent-mental","nt-urgent-mental","distress-training"]},{"id":"relationships","title":"Relationships and safety","tasks":["safety","relationships","legal"]},{"id":"children","title":"Children and caring","tasks":["children-education","child-wellbeing","parenting","baby","moving-childcare","carers","older"]},{"id":"work","title":"Work, study and benefits","tasks":["work","transition","rehabilitation","budgeting","claims"]},{"id":"connection","title":"Defence and community support","tasks":["new-entry","family-info","family-advocacy","defence-aware","groups","language","pastoral"]}];
const phoneLabel=url=>{const d=url.slice(4);return d.length===10&&d.startsWith('0')?d.slice(0,2)+' '+d.slice(2,6)+' '+d.slice(6):d.length===10&&/^(1800|1300)/.test(d)?d.slice(0,4)+' '+d.slice(4,7)+' '+d.slice(7):d;};
const supplementalRegion=(s,id)=>s.sourceRow.region_ids.includes(id==='palmerston'?'darwin':id==='gove'?'arnhem':id);
const contactsFor=s=>s.contactOptions||[...routeContactURLs(s).filter(u=>/^(tel:|sms:|mailto:)/.test(u)).map(u=>({href:u,label:u.startsWith('tel:')?'Call '+phoneLabel(u):u.startsWith('sms:')?'Text '+u.slice(4):'Email this service',channel:u.startsWith('tel:')?'phone':u.startsWith('sms:')?'text':'email'})),...routeWebActions(s).map(x=>({href:x.url,label:x.label,channel:'web'}))];
createSupportApp({urgentTask:{href:'#task/housing-tonight',label:'Nowhere to stay tonight?'},identity:'NT Defence family support',allHelp:'All Defence help',journeys,home,discover,discoveryFields,services:{...services,...supplementalServices},contactsFor,sourcesFor:s=>s.urls||s.sources||[],
 legacyChoice:value=>resolveLegacyIntent('defence',journeys,value),
 directory:{title:'Defence family resource details',entries:[...Object.values(services),...Object.values(supplementalServices)],needs:[...issues.map(i=>({id:i.issue_id,title:i.title})),{id:'shared-youth-housing',title:'Youth housing and homelessness support'}],regions:regionLabels,needMatches:(s,id)=>id==='shared-youth-housing'?s.sourceDataset==='homelessness':s.appearance.issue_id===id,regionMatches:(s,id)=>s.sourceDataset==='homelessness'?supplementalRegion(s,id):routeMatchesRegion(s.appearance,id),view:s=>s}
});
