import {preserveChoicePosition} from './support-progressive.mjs?v=20261006-results-final';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=value=>JSON.parse(JSON.stringify(value));
export function createSupportApp(config){
 const root=document.getElementById('finder'),embedded=window.self!==window.top;
 if('scrollRestoration' in history)history.scrollRestoration='manual';
 const views=new Map();let counter=0,generation=0,restoredURL='',handoff=null;
 let state={taskId:'',choiceIndex:null,refinements:{},narrowOpen:false,moreOpen:false};
 let directory={need:'',region:''};
 const taskFor=id=>config.journeys.find(t=>t.id===id);
 const helpChoice={topicId:'help',need:'default',title:'Help finding a service'};
 const currentChoice=()=>state.taskId==='help'?helpChoice:taskFor(state.taskId)?.choices[state.choiceIndex];
 const fieldValue=(field,facts=state.refinements)=>facts[field.id]??'';
 const safeHref=value=>{try{const u=new URL(value,location.href);return ['https:','http:','tel:','sms:','mailto:'].includes(u.protocol)||String(value).startsWith('#')?String(value):'';}catch{return '';}};
 const link=(href,label,classes='')=>{
  href=safeHref(href);if(!href)return '';
  const external=embedded&&/^https?:/.test(href);
  return `<a href="${esc(href)}"${classes?` class="${esc(classes)}"`:''}${external?` target="_blank" rel="noopener noreferrer" aria-label="${esc(label)} (opens in a new tab)"`:''}>${esc(label)}</a>`;
 };
 function prepareStaticLinks(){if(!embedded)return;document.querySelector('.page-shell').querySelectorAll('a[href]').forEach(a=>{if(!/^https?:/.test(a.getAttribute('href')))return;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',a.textContent.trim()+' (opens in a new tab)');});}
 const title=text=>{document.title=text===config.identity?`${text} | Lutheran Care`:`${text} | ${config.identity} | Lutheran Care`;};
 const navigation=()=>`<nav class="back-nav" aria-label="Support navigation">${link('#home',config.allHelp)}${handoff&&state.taskId==='help'?link('#task/'+handoff.taskId+(handoff.choiceIndex===null?'':'/'+handoff.choiceIndex),'Your original contacts','return-original'):''}<button type="button" class="text-button" data-action="reset">Start again</button></nav>`;
 function focusHeading(){root.querySelector('h1')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
 function remember(push=false,url=location.href){const key=`support-${generation}-${++counter}`,focus=document.activeElement;views.set(key,{generation,url:new URL(url,location.href).href,state:copy(state),directory:copy(directory),handoff:copy(handoff),focusId:root.contains(focus)?focus.id:'',scroll:scrollY});history[push?'pushState':'replaceState']({supportView:key,generation},'',url);}
 function restorePosition(view){const focus=document.getElementById(view.focusId);focus?.focus({preventScroll:true});window.scrollTo({top:view.scroll,behavior:'instant'});}
 function reset(){generation++;views.clear();handoff=null;directory={need:'',region:''};state={taskId:'',choiceIndex:null,refinements:{},narrowOpen:false,moreOpen:false};history.replaceState(null,'','#home');showHome();focusHeading();}
 function taskLink(task){return `<li>${link('#task/'+task.id,task.title,'task-link')}</li>`;}
 function showHome(){title(config.identity);root.innerHTML=`<h1 tabindex="-1">${esc(config.identity)}</h1>${config.urgentTask?`<p class="home-urgent-task">${link(config.urgentTask.href,config.urgentTask.label)}</p>`:''}<ul class="home-links home-entry-grid" aria-label="Choose the help you need">${config.home.map(entry=>`<li>${link(entry.href||'#start/'+entry.id,entry.title,'task-link')}</li>`).join('')}</ul><p class="human-link home-help">${link('#help','Not sure where to start? Get help finding a service')}</p>`;}
 function showMenu(entry){title(entry.title);root.innerHTML=`${navigation()}<h1 tabindex="-1">${esc(entry.title)}</h1><ul class="home-links" aria-label="Choose the help you need">${entry.tasks.map(id=>taskFor(id)).filter(Boolean).map(taskLink).join('')}</ul>`;}
 function dateLabel(value){if(/^\d{4}-\d\d-\d\d$/.test(value||''))return new Date(value+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});return value||'See official source';}
 function sourceDetails(service){const urls=[...new Set(config.sourcesFor(service))].filter(u=>/^https?:/.test(safeHref(u)));const parents=service.sourceIds||[service.id];return `<details class="service-source"><summary>Information checked ${esc(dateLabel(service.checked))}</summary><ul>${urls.map((u,i)=>`<li>${link(u,urls.length===1?'Official source':'Official source '+(i+1))}</li>`).join('')}${parents.filter(id=>config.directory.entries.some(s=>s.id===id)).map(id=>`<li>${link('#directory/'+id,'Resource details for this service')}</li>`).join('')}</ul></details>`;}
 function actionsFor(service,primary){const items=config.contactsFor(service).filter(c=>safeHref(c.href||c.url));let directUsed=false;return items.map(item=>{const url=item.href||item.url;const direct=!directUsed&&(item.channel!=='web'||item.label==='Search local services'||items.length===1);if(direct)directUsed=true;return link(url,item.label,primary&&direct?'button':direct?'contact-action':'official');}).join('');}
 function serviceCard(service,primary=false){const contact=service.publishedContact??service.contact??'';const notice=service.contactNotice||'';const intake=(service.catalogueId==='nt-central-intake'||Number(service.appearance?.catalogue_id)===86)&&!/outage/i.test([service.offer,service.access,notice].join(' '));return `<article class="service-card${primary?' service-card-primary':' alternative'}" data-service-id="${esc(service.id)}"><div class="service-card-head"><h3${primary?' class="primary-service-heading"':''}>${esc(service.name)}</h3><p class="offer">${esc(service.offer).replace(/\n/g,'<br>')}</p>${!primary?`<p class="area">${esc(service.area).replace(/\n/g,'<br>')}</p>`:''}${!primary&&service.fitNote?`<p class="fit-note">${esc(service.fitNote)}</p>`:''}</div><div class="contact-panel" aria-label="Contact ${esc(service.name)}">${intake?'<p class="notice">The published phone outage notice remains; current status is unconfirmed. Use the online enquiry form and allow 48 business hours. This is not help for tonight.</p>':''}<div class="service-actions">${actionsFor(service,primary)}</div>${primary?`<p class="area">${esc(service.area).replace(/\n/g,'<br>')}</p>`:''}${primary&&service.fitNote?`<p class="fit-note">${esc(service.fitNote)}</p>`:''}${notice?`<p class="contact-details">${esc(notice)}</p>`:''}${contact?`<p class="contact-details">${esc(contact).replace(/\n/g,'<br>')}</p>`:''}</div><div class="service-information">${service.cost?`<p class="cost"><strong>Cost:</strong> ${esc(service.cost)}</p>`:''}${service.hours?`<p class="hours"><strong>Hours:</strong> ${esc(service.hours)}</p>`:''}<p class="fit"><strong>Who can use it:</strong> ${esc(service.audience).replace(/\n/g,'<br>')}</p><p class="access"><strong>How to access it:</strong> ${esc(service.access).replace(/\n/g,'<br>')}</p></div>${sourceDetails(service)}</article>`;}
 function fieldMarkup(field,namespace='narrow'){
  const id=`${namespace}-${state.taskId}-${field.id}`,value=fieldValue(field);const wrap=body=>`<details class="optional-field-group" data-field-id="${esc(field.id)}" data-signature="${esc(JSON.stringify(field))}"${state.openFields?.includes(field.id)?' open':''}><summary>${esc(field.label)}</summary><div class="optional-field-body">${body}</div></details>`;const hint=field.hint?`<p class="question-hint" id="${id}-hint">${esc(field.hint)}</p>`:'';
  if(field.type==='number')return wrap(`<div class="optional-field" data-field-id="${esc(field.id)}" data-signature="${esc(JSON.stringify(field))}"><label class="field-label" for="${id}">${esc(field.label)}</label>${hint}<input type="number" class="age-input" id="${id}" name="${esc(field.id)}" value="${esc(value)}" min="0" max="120" step="1" inputmode="numeric"${field.hint?` aria-describedby="${id}-hint"`:''}><p class="field-error" id="${id}-error" role="status"></p></div>`);
  return wrap(`<fieldset class="choice-fieldset optional-field" data-field-id="${esc(field.id)}" data-signature="${esc(JSON.stringify(field))}"><legend>${esc(field.label)}</legend>${hint}<div class="choice-list choice-list-compact">${(field.options||[]).map((o,i)=>`<label class="choice-row" for="${id}-${i}"><input type="radio" id="${id}-${i}" name="${esc(field.id)}" value="${esc(o.value)}"${String(value)===String(o.value)||!value&&o.value==='unsure'?' checked':''}><span><strong>${esc(o.label)}</strong>${o.detail?`<small>${esc(o.detail)}</small>`:''}</span></label>`).join('')}</div></fieldset>`);
 }
 const allFields=()=>currentChoice()?config.discoveryFields(currentChoice(),state.refinements):[];
 function cleanFacts(next,previous={}){const fields=config.discoveryFields(currentChoice(),next);const allowed=new Set(fields.map(f=>f.id));const facts={};for(const field of fields){const value=next[field.id];if(value===undefined||value===null||value==='')continue;if(field.type==='number'){if(/^\d{1,3}$/.test(String(value))&&Number(value)<=120)facts[field.id]=String(Number(value));}else if(field.options?.some(o=>String(o.value)===String(value)))facts[field.id]=value;}
  if(next.region!==previous.region)for(const id of ['community','localCommunity','remoteArea','memberCentre'])delete facts[id];
  if(next.composition!==previous.composition&&(['couple','family'].includes(next.composition)||['couple','family'].includes(previous.composition)))delete facts.age;
  if(next.recipient!==previous.recipient||next.role!==previous.role)for(const id of ['age','veteranCard','dvaTravel','travelFunding','healthFunding','remotePosting','veteranCare','dependant'])if(allowed.has(id))delete facts[id];
  return facts;
 }
 function reconcileFields(fields){const container=document.getElementById('discovery-fields'),old=new Map([...container.children].map(n=>[n.dataset.fieldId,n])),keep=new Set();fields.forEach((field,index)=>{const template=document.createElement('template');template.innerHTML=fieldMarkup(field);const proposed=template.content.firstElementChild;let node=old.get(field.id);if(!node||node.dataset.signature!==proposed.dataset.signature){node?.remove();node=proposed;}node.open=Boolean(state.openFields?.includes(field.id));const value=fieldValue(field);node.querySelectorAll('input[type="radio"]').forEach(i=>{i.checked=String(i.value)===String(value)||!value&&i.value==='unsure';});const number=node.querySelector('input[type="number"]');if(number&&document.activeElement!==number)number.value=value;if(container.children[index]!==node)container.insertBefore(node,container.children[index]||null);keep.add(node);});[...container.children].forEach(n=>{if(!keep.has(n))n.remove();});}
 function areaMarkup(field){if(!field)return '';return `<label for="discovery-area">Area</label><select id="discovery-area" name="region" aria-label="Area for these contacts">${field.options.map(o=>`<option value="${esc(o.value)}"${String(o.value)===String(fieldValue(field))||!fieldValue(field)&&o.value==='unsure'?' selected':''}>${esc(o.label)}</option>`).join('')}</select>`;}
 function selectedLabel(fields){return fields.filter(f=>f.id!=='region'&&state.refinements[f.id]!==undefined&&state.refinements[f.id]!==''&&!['unsure','standard'].includes(state.refinements[f.id])).map(f=>f.type==='number'?`Age ${state.refinements[f.id]}`:f.options.find(o=>String(o.value)===String(state.refinements[f.id]))?.label).filter(Boolean).join(' · ');}
 function renderContacts(){const choice=currentChoice(),result=config.discover(choice,state.refinements);const all=[...new Set([...(result.ids||[]),...(result.moreIds||[]),...(result.allIds||[])])];const get=id=>result.servicesById?.[id]||config.services[id];const primary=(result.ids||[]).filter(id=>get(id));const others=all.filter(id=>!primary.includes(id)&&get(id));const intro=result.note?`<p class="notice result-notice">${esc(result.note)}</p>`:'';const contacts=document.getElementById('discovery-contacts');
  contacts.innerHTML=primary.length?`${result.noteBefore?intro:''}<div class="contact-shortlist">${primary.map((id,index)=>serviceCard(get(id),index===0)).join('')}</div>${!result.noteBefore?intro:''}${others.length?`<details class="other-options" id="other-options"${state.moreOpen?' open':''}><summary>Other service options (${others.length})</summary><div class="other-contact-list">${others.map(id=>serviceCard(get(id))).join('')}</div></details>`:''}${result.say?`<details class="say"><summary>What could I say when I contact them?</summary><p>“${esc(result.say)}”</p></details>`:''}`:`<p>No suitable contact is listed for these details. Leave a detail unknown, choose another task or get help finding a service.</p>${intro}`;
  document.getElementById('discovery-recovery').innerHTML=`${state.taskId!=='help'?link('#help','Find another way to get help','request-help'):''}<button type="button" class="text-button" data-action="print">Print these contacts</button>`;
  document.getElementById('discovery-status').textContent=primary.length?`${primary.length} contacts shown${others.length?'; other service options are available below':''}.`:'No listed contact for these details.';
 }
 function updateResults(){const fields=allFields(),area=fields.find(f=>f.id==='region');const areaHost=document.getElementById('discovery-area-control');if(area){const select=areaHost.querySelector('select');const signature=JSON.stringify(area.options);if(!select||areaHost.dataset.signature!==signature){areaHost.innerHTML=areaMarkup(area);areaHost.dataset.signature=signature;}else select.value=fieldValue(area)|| (area.options.some(o=>o.value==='unsure')?'unsure':'');}else areaHost.innerHTML='';
  reconcileFields(fields.filter(f=>f.id!=='region'));const panel=document.getElementById('narrow-contacts');panel.hidden=!fields.some(f=>f.id!=='region');panel.open=state.narrowOpen;document.getElementById('chosen-refinements').textContent=selectedLabel(fields);renderContacts();
 }
 function taskChoices(task){if(task.choices.length===1)return '';return `<fieldset class="choice-fieldset task-question"><legend>What would help?</legend><div class="choice-list">${task.choices.map((c,i)=>`<label class="choice-row" for="task-choice-${task.id}-${i}"><input type="radio" id="task-choice-${task.id}-${i}" name="task-choice" value="${i}"${state.choiceIndex===i?' checked':''}><span><strong>${esc(c.title)}</strong></span></label>`).join('')}</div></fieldset>`;}
 function showTask(){const task=state.taskId==='help'?{id:'help',title:'Help finding a service',choices:[helpChoice]}:taskFor(state.taskId);if(!task)return showHome();title(task.title);root.innerHTML=`${navigation()}<h1 tabindex="-1">${esc(task.title)}</h1>${handoff&&state.taskId==='help'?`<p class="handoff-context">${esc(taskFor(handoff.taskId)?.choices[handoff.choiceIndex]?.title||taskFor(handoff.taskId)?.title)}</p>`:''}<div id="support-answers" tabindex="-1">${taskChoices(task)}</div><section class="discovery" id="support-contacts" aria-labelledby="support-contacts-heading"${currentChoice()?'':' hidden'}><div class="discovery-heading"><h2 id="support-contacts-heading">Contact a service</h2><div id="discovery-area-control" class="area-control"></div></div><p id="chosen-refinements" class="chosen-refinements"></p><div class="discovery-layout"><details class="refinement-panel" id="narrow-contacts"><summary>Narrow contacts <span>(optional)</span></summary><div id="discovery-fields"></div></details><div class="discovery-results"><p id="discovery-status" class="sr-only" role="status" aria-live="polite"></p><div id="discovery-contacts"></div><div class="result-bottom" id="discovery-recovery"></div></div></div></section>`;if(currentChoice())updateResults();}
 function showDirectory(record=''){title(config.directory.title);const needs=config.directory.needs,regions=config.directory.regions;root.innerHTML=`${navigation()}<h1 tabindex="-1">${esc(config.directory.title)}</h1><div class="directory-filters"><label for="directory-need">Need<select id="directory-need"><option value="">All needs</option>${needs.map(n=>`<option value="${esc(n.id)}"${directory.need===n.id?' selected':''}>${esc(n.title)}</option>`).join('')}</select></label><label for="directory-region">Region<select id="directory-region"><option value="">All published areas</option>${Object.entries(regions).map(([id,label])=>`<option value="${esc(id)}"${directory.region===id?' selected':''}>${esc(label)}</option>`).join('')}</select></label></div><p id="directory-count" role="status" aria-live="polite"></p><div id="directory-records"></div>`;refreshDirectory(record);}
 function refreshDirectory(record=''){const items=config.directory.entries.filter(s=>(!directory.need||config.directory.needMatches(s,directory.need))&&(!directory.region||config.directory.regionMatches(s,directory.region)));document.getElementById('directory-count').textContent=`${items.length} entries`;document.getElementById('directory-records').innerHTML=items.map(s=>`<details class="directory-card" id="record-${esc(s.id)}"${s.id===record?' open':''}><summary>${esc(s.name)}</summary>${serviceCard(config.directory.view(s,directory.region))}${s.issueNote?`<p class="notice">${esc(s.issueNote)}</p>`:''}</details>`).join('')||`<p>No entry is listed for both filters. ${link('#directory','Clear filters','clear-filters')} or ${link('#help','get help finding a service')}.</p>`;}
 function routeTo(hash){const value=hash.replace(/^#/,'')||'home';if(value==='home'){state={taskId:'',choiceIndex:null,refinements:{},narrowOpen:false,moreOpen:false};showHome();return;}if(value.startsWith('start/')){const entry=config.home.find(e=>e.id===value.slice(6));if(entry){state={taskId:'',choiceIndex:null,refinements:{},narrowOpen:false,moreOpen:false};showMenu(entry);return;}}
  if(value.startsWith('directory')){showDirectory(decodeURIComponent(value.split('/').slice(1).join('/')));return;}
  if(value==='help'){state={taskId:'help',choiceIndex:0,refinements:state.refinements.region?{region:state.refinements.region}:{},narrowOpen:false,moreOpen:false};showTask();return;}
  let id,index;if(value.startsWith('task/')){const parts=value.split('/');id=parts[1];index=parts.length===3&&/^\d+$/.test(parts[2])?Number(parts[2]):null;}else{const old=config.legacyChoice(value);if(old){if(old.tasks){showMenu(old);return;}if(old.home){showHome();return;}if(old.menu){const entry=config.home.find(e=>e.id===old.menu);if(entry){showMenu(entry);return;}}id=old.id;index=old.index;}}
  const task=taskFor(id);if(!task){showHome();return;}const selected=Number.isInteger(index)&&task.choices[index]?index:task.choices.length===1?0:null;const area=state.refinements.region;state={taskId:id,choiceIndex:selected,refinements:area?{region:area}:{},narrowOpen:false,moreOpen:false};showTask();
 }
 function changeTask(control){const task=taskFor(state.taskId),index=Number(control.value);if(!task?.choices[index]||index===state.choiceIndex)return;remember();const before={...state.refinements};state.choiceIndex=index;state.refinements=cleanFacts(before,before);state.moreOpen=false;preserveChoicePosition(control,()=>{root.querySelectorAll('input[name="task-choice"]').forEach(i=>i.checked=Number(i.value)===index);document.getElementById('support-contacts').hidden=false;updateResults();});remember(true,'#task/'+task.id+'/'+index);}
 function changeRefinement(control){const field=allFields().find(f=>f.id===control.name);if(!field)return;let value=control.value;if(field.type==='number'){if(value!==''&&(!/^\d{1,3}$/.test(value)||Number(value)>120)){control.setAttribute('aria-invalid','true');document.getElementById(control.id+'-error').textContent='Enter an age in whole years, or leave this blank.';return;}control.removeAttribute('aria-invalid');document.getElementById(control.id+'-error').textContent='';if(value!=='')value=String(Number(value));}else if(!field.options?.some(o=>String(o.value)===String(value)))return;
  if((state.refinements[field.id]??'')===value)return;remember();const previous={...state.refinements};let next={...previous,[field.id]:value};state.refinements=cleanFacts(next,previous);if(control.closest('#narrow-contacts')){state.narrowOpen=true;state.openFields=[...new Set([...(state.openFields||[]),field.id])];}state.moreOpen=false;preserveChoicePosition(control,updateResults);remember(true);
 }
 root.addEventListener('change',event=>{const control=event.target;if(!root.contains(control))return;if(control.id==='directory-need'||control.id==='directory-region'){directory[control.id==='directory-need'?'need':'region']=control.value;refreshDirectory();remember();return;}if(control.name==='task-choice'&&control.closest('#support-answers'))changeTask(control);else if(control.closest('#discovery-fields')||control.id==='discovery-area')changeRefinement(control);});
 root.addEventListener('submit',e=>e.preventDefault());
 root.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input[type="radio"]')){e.preventDefault();e.target.click();}});
 root.addEventListener('toggle',e=>{if(e.target.classList?.contains('optional-field-group')){const id=e.target.dataset.fieldId;state.openFields=e.target.open?[...new Set([...(state.openFields||[]),id])]:(state.openFields||[]).filter(f=>f!==id);}if(e.target.id==='narrow-contacts')state.narrowOpen=e.target.open;if(e.target.id==='other-options')state.moreOpen=e.target.open;},true);
 root.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button?.dataset.action==='reset'){event.preventDefault();reset();return;}if(button?.dataset.action==='print'){window.print();return;}const a=event.target.closest('a[href^="#"]');if(!a||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;if(a.dataset.pageJump)return;event.preventDefault();if(a.classList.contains('request-help'))handoff=copy(state);else if(a.classList.contains('return-original')&&handoff){remember();state=copy(handoff);handoff=null;history.pushState(null,'',a.hash);showTask();remember();focusHeading();return;}else if(a.hash==='#help')handoff=null;if(a.classList.contains('clear-filters'))directory={need:'',region:''};remember();if(a.hash!==location.hash)history.pushState(null,'',a.hash);routeTo(a.hash);remember();focusHeading();});
 document.addEventListener('click',event=>{const a=event.target.closest('a[data-page-jump]');if(!a)return;const target=document.getElementById(a.dataset.pageJump);if(!target)return;event.preventDefault();target.focus({preventScroll:true});target.scrollIntoView({block:'start'});});
 document.querySelector('.skip-link')?.addEventListener('click',e=>{e.preventDefault();document.getElementById('main').focus();document.getElementById('main').scrollIntoView();});
 window.addEventListener('popstate',event=>{restoredURL=location.href;const view=views.get(event.state?.supportView);if(!view||view.generation!==generation||view.url!==location.href){state={taskId:'',choiceIndex:null,refinements:{},narrowOpen:false,moreOpen:false};routeTo(location.hash);remember();focusHeading();return;}state=copy(view.state);directory=copy(view.directory);handoff=copy(view.handoff);if(location.hash.startsWith('#directory'))showDirectory(decodeURIComponent(location.hash.split('/').slice(1).join('/')));else if(state.taskId)showTask();else routeTo(location.hash);restorePosition(view);});
 window.addEventListener('hashchange',()=>{if(restoredURL===location.href){restoredURL='';return;}restoredURL='';routeTo(location.hash);remember();focusHeading();});
 window.addEventListener('beforeprint',()=>root.querySelectorAll('details').forEach(d=>{d.dataset.printOpen=d.open?'yes':'no';d.open=true;}));
 window.addEventListener('afterprint',()=>root.querySelectorAll('details[data-print-open]').forEach(d=>{d.open=d.dataset.printOpen==='yes';delete d.dataset.printOpen;}));
 routeTo(location.hash);remember();prepareStaticLinks();
}
